name: Deployment pipeline

on:
  push:
    branches:
      - Xmain
  pull_request:
    branches: [Xmain]
    types: [opened, synchronize]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ vars.MONGO_URI }}
      PORT: ${{ vars.PORT }}
      SECRET: ${{ vars.SECRET }}
      TEST_MONGO_URI: ${{ vars.TEST_MONGO_URI }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install dependencies
        run: |
          npm run install:all
          npm install @rollup/rollup-linux-x64-gnu --no-save
      - name: Check style
        run: npm run lint
      - name: Test backend
        run: npm run test -w bloglist-backend
      - name: Test frontend
        run: npm run test -w bloglist-frontend
      - name: Run npm run build
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests
        run: npm run test:e2e
  deploy:
    needs: [build_and_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
